fx_version 'cerulean'
game 'gta5'
lua54 'yes'
use_experimental_fxv2_oal 'yes'

name 'w2f-ambulance'
author 'w2f'
description 'w2f-ambulance — EMS job, hospital, pharmacy, death/laststand, and injury system for Qbox'
version '1.4.0'

ox_lib 'locale'

ui_page 'web/dist/index.html'

dependencies {
    'qbx_core',
    'ox_lib',
    'ox_inventory',
    'ox_target',
    'oxmysql',
}

shared_scripts {
    '@ox_lib/init.lua',
    '@qbx_core/modules/lib.lua',
    'shared/init.lua',
    'config/systems.lua',
    'config/ranks.lua',
    'config/equipment.lua',
    'shared/constants.lua',
    'shared/access.lua',
    'shared/core.lua',
    'shared/placeables.lua',
    'medical/shared/main.lua',
    'config/prescription.lua',
    'config/minigame.lua',
    'config/public_records.lua',
    'shared/care.lua',
    'config/placeables.lua',
    'config/training_dummy.lua',
    'config/garage.lua',
    'config/triage.lua',
}

client_scripts {
    '@qbx_core/modules/playerdata.lua',
    'client/namespace.lua',
    'medical/client/damage/apply-damage-effects.lua',
    'medical/client/damage/damage.lua',
    'medical/client/main.lua',
    'medical/client/wounding.lua',
    'medical/client/laststand.lua',
    'medical/client/dead.lua',
    'medical/client/load-unload.lua',
    'medical/client/setdownedstate.lua',
    'medical/client/compat.lua',
    'client/medical_api.lua',
    'client/core.lua',
    'client/care.lua',
    'client/duty_blips.lua',
    'client/animations.lua',
    'client/garage_preview.lua',
    'client/garage_markers.lua',
    'client/ui.lua',
    'client/catalog_client.lua',
    'client/stream.lua',
    'client/training_dummy.lua',
    'client/placeables.lua',
    'client/triage.lua',
    'client/tablet.lua',
    'client/radial.lua',
    'client/main.lua',
    'client/minigame.lua',
    'client/reception.lua',
    'client/hospital.lua',
    'client/job.lua',
    'client/laststand.lua',
    'client/setdownedstate.lua',
    'client/medical_items.lua',
    'client/prescription_effects.lua',
    'client/prescription_pharmacy.lua',
    'client/prescription_ems.lua',
    'client/public_records.lua',
    'client/qbx_compat.lua',
}

server_scripts {
    '@oxmysql/lib/MySQL.lua',
    'server/namespace.lua',
    'server/bootstrap.lua',
    'medical/server/main.lua',
    'server/database.lua',
    'server/setup.lua',
    'server/identity.lua',
    'server/care.lua',
    'server/catalog.lua',
    'server/logging.lua',
    'server/tablet.lua',
    'server/public_records.lua',
    'server/records.lua',
    'server/triage.lua',
    'server/training_dummy.lua',
    'server/placeables.lua',
    'server/main.lua',
    'server/duty_blips.lua',
    'server/hospital.lua',
    'server/prescription.lua',
    'server/qbx_compat.lua',
    'server/commands.lua',
}

files {
    'locales/*.json',
    'config/client.lua',
    'config/shared.lua',
    'config/triage.lua',
    'config/server.lua',
    'medical/config/client.lua',
    'medical/config/shared.lua',
    'web/dist/index.html',
    'web/dist/styles.css',
    'web/dist/ui.js',
    'web/dist/equipment.js',
    'web/dist/garage.js',
    'web/dist/tablet.js',
    'web/dist/minigame.js',
    'web/dist/public-records.js',
    'stream/dummy.ytyp',
}

data_file 'DLC_ITYP_REQUEST' 'stream/dummy.ytyp'

exports {
    'CheckIn',
    'CreateRecord',
    'IssuePrescription',
    'usePrescription',
    'useBandage',
    'useFirstaid',
    'useIfaks',
    'usePainkillers',
    'useHaveitol',
    'useDeadTired',
    'useFentanyl',
    'useOxycodone',
    'useWakeyWakey',
    'useCommandTablet',
    'useTrainingDummy',
    'OpenCommandTablet',
    'RunCareMinigame',
    'CreatePublicRecord',
    'GetPublicRecords',
    'Revive',
    'Heal',
    'HealPartially',
    'GetPlayerStatus',
    'IsDead',
    'IsLaststand',
    'GetDeathTime',
    'GetLaststandTime',
    'IncrementDeathTime',
    'IncrementLaststandTime',
    'GetRespawnHoldTimeDeprecated',
    'MakePedLimp',
    'SendBleedAlert',
    'PlayDeadAnimation',
    'KillPlayer',
    'AllowRespawn',
    'DisableRespawn',
    'StartLastStand',
    'MakePlayerBlackout',
    'MakePlayerFadeOut',
    'RemoveBleed',
    'EnableBleeding',
    'DisableBleeding',
    'EnableDamageEffects',
    'DisableDamageEffects',
    'SetDeathState',
    'ResetMinorInjuries',
    'DisableDeathScreen',
    'EnableRespawn',
    'RespawnPlayer',
}
